import test from 'node:test';import assert from 'node:assert/strict';
import {Walker,blocked,groundAt} from '../src/world.mjs';
import {toWorld,toLocal,levels,start,initialView} from '../src/data/unifiedLayout.mjs';
import {routeWaypoints,gateOpenings,documentedNineSteps,approachSurfaces,approachRamps,approachRetainingWalls,mainPlaza} from '../src/data/hondanRoute.mjs';
function drive(p,points){for(const [x,z] of points){const w=toWorld(x,z);let reached=false;for(let i=0;i<3600;i++){const dx=w.x-p.x,dz=w.z-p.z,n=Math.hypot(dx,dz);if(n<.035){reached=true;break;}p.step(dx/n*2,dz/n*2,1/120);}assert.ok(reached,`Blocked at ${x},${z}: ${JSON.stringify(p)}`);}}
const ascent=[[0,8],[-2.8,8],[-2.8,4.5],[-2.8,-4.8],[2.8,-4.8],[2.8,-4.5],[2.8,4.8],[-2.8,4.8],[-2.8,4.5],[-2.8,-4.8],[0,-4.8],[0,-2]];
const spawnLocal=[-2,60];
function reachCourtyardFromSpawn(p){drive(p,[...routeWaypoints].reverse());drive(p,[[0,13.1]]);}
test('respawn is the Honmaru plaza overview point with cinematic initial view',()=>{const p=new Walker(),l=toLocal(p.x,p.z),s=toLocal(start.x,start.z);assert.ok(Math.abs(l.x-s.x)<1e-9&&Math.abs(l.z-s.z)<1e-9);assert.ok(Math.abs(l.x-spawnLocal[0])<1e-9&&Math.abs(l.z-spawnLocal[1])<1e-9);assert.equal(p.y,.05);assert.equal(initialView.yaw,-.04);assert.equal(initialView.pitch,.17);assert.ok(l.z>=mainPlaza.z0&&l.z<=mainPlaza.z1);});
test('one continuous spawn-to-top-and-back route crosses plaza, gates and keep without teleporting',()=>{const p=new Walker();reachCourtyardFromSpawn(p);drive(p,ascent);assert.equal(p.y,21.8);drive(p,[...ascent].reverse());drive(p,[[0,13.1]]);drive(p,routeWaypoints);drive(p,[spawnLocal]);assert.ok(p.y<=mainPlaza.y+.02,`plaza y=${p.y}`);const l=toLocal(p.x,p.z);assert.ok(Math.abs(l.x-spawnLocal[0])<.05&&Math.abs(l.z-spawnLocal[1])<.05);});
test('entrance is open but neighbouring original wall and inferred inner wall remain solid',()=>{for(const x of [0,2.4,-2.4]){const p=toWorld(x,10.29);assert.equal(blocked(p.x,9.2,p.z),x!==0);}const p=toWorld(0,10.29);assert.equal(groundAt(p.x,p.z,9.4),9.2);});
test('best-fit courtyard gate is cut only at its registered opening box',()=>{const g=gateOpenings[0],wallZ=16.08,inside=toWorld((g.x0+g.x1)/2,wallZ),neighbour=toWorld(2.2,wallZ);assert.equal(blocked(inside.x,9.2,inside.z),false);assert.equal(blocked(neighbour.x,9.2,neighbour.z),true);assert.equal(groundAt(inside.x,inside.z,9.4),9.2);});
test('spawn reaches the courtyard and returns to the georeferenced Honmaru plaza without teleporting',()=>{const p=new Walker();reachCourtyardFromSpawn(p);assert.equal(p.y,9.2);drive(p,routeWaypoints);drive(p,[spawnLocal]);assert.ok(p.y<=mainPlaza.y+.02,`plaza y=${p.y}`);let l=toLocal(p.x,p.z);assert.ok(Math.abs(l.x-spawnLocal[0])<.05&&Math.abs(l.z-spawnLocal[1])<.05);drive(p,[...routeWaypoints].reverse());drive(p,[[0,13.1]]);assert.equal(p.y,9.2);l=toLocal(p.x,p.z);assert.ok(Math.abs(l.x)<.05&&Math.abs(l.z-13.1)<.05);});
test('official nine-step count is the only explicit exterior counted stair run',()=>{assert.equal(documentedNineSteps.length,9);for(let i=1;i<documentedNineSteps.length;i++)assert.ok(documentedNineSteps[i].y<documentedNineSteps[i-1].y);assert.ok(documentedNineSteps.every((s,i)=>s.step===i+1&&s.stepCount===9));const counted=approachSurfaces.filter(s=>s.step);assert.equal(counted.length,9);assert.ok(counted.every(s=>s.stepCount===9));});
test('lower Honmaru rise is a narrow continuous grade with only low sidewalls',()=>{assert.equal(approachRamps.length,1);const r=approachRamps[0];assert.equal(r.y0,7.85);assert.equal(r.y1,.05);assert.ok(r.z1-r.z0>14);const z=(r.z0+r.z1)/2,x=(r.x0+r.x1)/2,w=toWorld(x,z),expected=(r.y0+r.y1)/2;assert.ok(Math.abs(groundAt(w.x,w.z,expected+.21)-expected)<1e-8);assert.equal(blocked(w.x,expected,w.z),false);assert.equal(approachRetainingWalls.length,6);for(const b of approachRetainingWalls){assert.ok(b.x1-b.x0<=.56);assert.ok(Math.abs((b.top0-b.bottom0)-1.7)<1e-9);assert.ok(Math.abs((b.top1-b.bottom1)-1.7)<1e-9);const midZ=(b.z0+b.z1)/2,midY=((b.bottom0+b.top0)+(b.bottom1+b.top1))/4,bw=toWorld((b.x0+b.x1)/2,midZ);assert.equal(blocked(bw.x,midY,bw.z),true);}});
test('upper exterior constrains walker even at an open window sill',()=>{const p=new Walker(),w=toWorld(0,-2);Object.assign(p,w,{y:21.8});for(let i=0;i<1200;i++)p.step(4,0,1/120);assert.ok(toLocal(p.x,p.z).x<levels[3].width/2);assert.equal(p.y,21.8);});
